### ISSUE TITLE
phpmyadmin exited with code 139

### ISSUE THREAD

**Issue by AhmedMItman** [bitnami/bitnami-docker-phpmyadmin#18]
phpmyadmin              | /opt/bitnami/base/helpers: line 13:    26 Segmentation fault      (core dumped) nami ${NAMI_DEBUG:+--log-level ${NAMI_LOG_LEVEL:-trace}} initialize ${module} $inputs "${@:2}"

**Comment by marcosbc** [comment]
Hi,

Unfortunately we've been unable to reproduce any issue with the Bitnami phpMyAdmin container. We used example `docker-compose.yml` shown [here](https://github.com/bitnami/bitnami-docker-phpmyadmin#using-docker-compose).

In order to better understand what is happening and how, could you please fill the information below (extracted from the text in the "New issue" form)?

____

 **Description:**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version:**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
