### ISSUE TITLE
Support the ability to extend the container configuration to enable such things as multiple databases

### ISSUE THREAD

**Issue by leopoldodonnell** [bitnami/bitnami-docker-phpmyadmin#22]
**Description**

We are moving our _pet_ _phpmyadmin_ from a single instance into a Kubernetes cluster. The stable Helm chart using `bitnami-docker-phpmyadmin` would be the preferred way to go. We currently support multiple databases from our instance that our operations people use to dig into problems but the current solution will only allow a single database host.

**Steps to reproduce the issue:**

1. Create a configmap with a config.inc.php If using Kubernetes
2. Hack the Helm chart, to mount the configmap to the config.inc.php (Note: you can't make it read-only 😢 ) if using Kubernete or just volume mount it if using docker directly

**Describe the results you received:**

It fails! The initialization scripts in the container using `nami` try to overwrite it.

**Describe the results you expected:**

I would expect to be able to define my own config.inc.php, or define one that would be included if supplied.

**Version**

image version is: 4.8.4
- Output of `docker version`:

```
Docker version 18.09.1, build 4c52b90
```

** Additional Discussion **

I'd be happy to develop a PR, but I'm afraid it would be rejected. Are there any guidelines that would help to craft an appropriate solution to this?

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion, we will evaluate it. If you want to contribute, you can do either one of the following things:

  - Check the nami logic inside the container `/.root/nami/components/com.bitnami.phpmyadmin/`, which is node.js code, and propose here (I am afraid we do not have that code shared publicly) how these files would be modified
  - Create PR in our bitnami phpmyadmin chart

**Comment by yctn** [comment]
i would like this to. that it can support multiple databases. any ETA/plans to add it?

**Comment by andresbono** [comment]
Thanks for showing your interests @yctn. I'm afraid we don't have an ETA for this feature.

**Comment by kurt---** [comment]
+1 for this feature-request

**Comment by javsalgar** [comment]
As soon as we have more news, we will update this ticket

**Comment by FranciscoDA** [comment]
Hello,

We're in a scenario similar to the one described by @leopoldodonnell , except we want to set up a phpmyadmin controluser, among other settings.

We've gotten around hacking the deployment.yaml file to mount a volume from a configmap so that it writes a configuration file into `/etc/phpmyadmin/config.inc.php` like phpmyadmin's documentation states. However, it seems that this image's phpmyadmin won't read the config file there, instead it will read `/opt/bitnami/phpmyadmin/config.inc.php` (which seems to be copied to `/bitnami/phpmyadmin/config.inc.php` for some reason?)

However, we're at a dead end because mounting the configmap on `/opt/bitnami/phpmyadmin` won't let phpmyadmin use that directory: `Error executing 'postInstallation': EROFS: read-only file system, mkdir '/opt/bitnami/phpmyadmin/tmp`.

Maybe the docker image could be edited so that `/opt/bitnami/phpmyadmin/config.inc.php` becomes a dumb include to `/etc/phpmyadmin/config.inc.php`?

**Comment by javsalgar** [comment]
Hi,

ConfigMaps are mounted read-only, so that could explain part of the issue. As a workaround, we are adding support for custom commands and args, as well as custom mounts so more cases can be covered. I think that, for the meantime, it could work for your case, right?

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on the backlog and there are no plans to work on it in the short term.

In the same way, please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-phpmyadmin#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
